-- =====================================================================
--  DocFlow : Initial Schema Creation (Version 1)
--  Compatible with Oracle 19c / 21c / 23c
--  Purpose: Core data structures for document storage, requests, and audit trail.
-- =====================================================================

-- ================================================================
-- TABLE: DOC_METADATA
-- Purpose : Stores information about each uploaded document.
-- ================================================================
CREATE TABLE DOC_METADATA (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Unique identifier for each document
    DOC_NAME        VARCHAR2(255) NOT NULL,        -- Original file name or logical document title
    DOC_TYPE        VARCHAR2(100),                 -- Category or type (e.g., POLICY, CONTRACT, INVOICE)
    UPLOADED_BY     VARCHAR2(100),                 -- Username or ID of the uploader
    UPLOADED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,-- Upload timestamp
    STATUS          VARCHAR2(30) DEFAULT 'PENDING' -- Workflow state (PENDING / APPROVED / REJECTED)
);

-- ================================================================
-- TABLE: DOC_REQUEST
-- Purpose : Tracks maker/checker or workflow requests made on documents.
-- ================================================================
CREATE TABLE DOC_REQUEST (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Unique request ID
    DOC_ID          NUMBER REFERENCES DOC_METADATA(ID),   -- Links to DOC_METADATA.ID
    REQUEST_TYPE    VARCHAR2(50),             -- Type of request (e.g., APPROVAL, UPDATE, REUPLOAD)
    REQUEST_BY      VARCHAR2(100),            -- User initiating the request
    REQUEST_AT      TIMESTAMP DEFAULT SYSTIMESTAMP, -- Timestamp of request initiation
    COMMENTS        VARCHAR2(1000)            -- Optional remarks or justification text
);

-- ================================================================
-- TABLE: DOC_AUDIT
-- Purpose : Centralized audit log for all user/admin actions.
-- ================================================================
CREATE TABLE DOC_AUDIT (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Unique audit record ID
    ACTION          VARCHAR2(100),           -- Action performed (UPLOAD, APPROVE, DELETE, etc.)
    USER_NAME       VARCHAR2(100),           -- Who performed the action
    ACTION_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP, -- When it happened
    DETAILS         CLOB                     -- Free-form details (e.g., JSON snapshot, remarks)
);

-- ================================================================
-- SEQUENCE: SEQ_DOC_AUDIT
-- Purpose : Optional manual sequence for explicit audit inserts (legacy DB compatibility).
-- ================================================================
CREATE SEQUENCE SEQ_DOC_AUDIT START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================================================================
-- END OF V1__init_schema.sql
-- =====================================================================
