-- ================================================
--  DOCFLOW : Closure Rules Framework - Core Tables
--  Oracle 19 compatible (no 23+ features)
-- ================================================

CREATE TABLE DOC_RULES (
    RULE_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RULE_TYPE        VARCHAR2(30) NOT NULL,   -- e.g. 'CHILD_STATUS', 'DATE_CHECK'
    TARGET_ENTITY    VARCHAR2(30) NOT NULL,   -- e.g. 'DOC_CHILD'
    EXPRESSION       VARCHAR2(4000) NOT NULL, -- e.g. "status = 'APPROVED'" or "expiry_date < SYSDATE"
    DESCRIPTION      VARCHAR2(255),
    ACTIVE           CHAR(1) DEFAULT 'Y' CHECK (ACTIVE IN ('Y','N')),
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DOC_RULE_BINDINGS (
    BINDING_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RULE_ID          NUMBER NOT NULL REFERENCES DOC_RULES(RULE_ID),
    APPLIES_TO       VARCHAR2(30) NOT NULL,   -- e.g. 'DOCUMENT', 'PROJECT'
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DOC_RULE_AUDIT (
    AUDIT_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_ID           NUMBER NOT NULL,
    RULE_ID          NUMBER NOT NULL REFERENCES DOC_RULES(RULE_ID),
    RESULT           VARCHAR2(10) NOT NULL,   -- 'PASS' / 'FAIL'
    DETAILS          VARCHAR2(1000),
    EVALUATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  DOC_RULES         IS 'Defines configurable closure rules (status/date based)';
COMMENT ON TABLE  DOC_RULE_BINDINGS IS 'Maps rules to document types';
COMMENT ON TABLE  DOC_RULE_AUDIT    IS 'Audit log for rule evaluations per document';
