-- =======================================================
-- DOCFLOW : Parent and Child Document Schema
-- Oracle 19 Compatible (no 23+ syntax)
-- =======================================================

-- -------------------------------------------------------
-- Parent Document Table
-- -------------------------------------------------------
CREATE TABLE DOC_PARENT (
    PARENT_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_NAME       VARCHAR2(255) NOT NULL,
    STATUS         VARCHAR2(30) DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT','OPEN','REVIEW','APPROVED','REJECTED','COMPLETED')),
    UPLOADED_BY    VARCHAR2(100),
    UPLOADED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    DESCRIPTION    VARCHAR2(500),
    CLIENT_DOC_ID  VARCHAR2(50),       -- future-friendly field for configurable client ID
    SYSTEM_DOC_ID  VARCHAR2(50),       -- system-generated internal ID
    LAST_UPDATED   TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  DOC_PARENT IS 'Stores parent-level documents uploaded by users.';
COMMENT ON COLUMN DOC_PARENT.CLIENT_DOC_ID IS 'Client-visible ID based on configurable pattern.';
COMMENT ON COLUMN DOC_PARENT.SYSTEM_DOC_ID IS 'System-generated globally unique document ID.';

-- -------------------------------------------------------
-- Child Document Table
-- -------------------------------------------------------
CREATE TABLE DOC_CHILD (
    CHILD_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PARENT_ID     NUMBER NOT NULL REFERENCES DOC_PARENT(PARENT_ID),
    STATUS        VARCHAR2(30) CHECK (STATUS IN ('DRAFT','REVIEW','APPROVED','REJECTED')),
    EXPIRY_DATE   DATE,
    COMMENTS      VARCHAR2(500),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  DOC_CHILD IS 'Stores child rows derived from Excel or detailed attachments.';
COMMENT ON COLUMN DOC_CHILD.STATUS IS 'Status per row, used in closure rule evaluation.';
COMMENT ON COLUMN DOC_CHILD.EXPIRY_DATE IS 'Used for date-based rule checks.';
