CREATE TABLE CLIENTCONFIG (
    CLIENT_ID          VARCHAR2(50 CHAR) PRIMARY KEY,
    ID_FORMAT          VARCHAR2(100 CHAR),
    UPLOAD_FIELDS_JSON CLOB,
    THEME_JSON         CLOB
);

COMMENT ON TABLE CLIENTCONFIG IS 'Client-specific configuration, upload fields and themes';

CREATE INDEX IDX_DOCPARENT_CLIENT ON DOCPARENT (CLIENT_ID);
CREATE INDEX IDX_DOCPARENT_STATUS ON DOCPARENT (STATUS);